name: WakaTime Coding Stats

on:
  schedule:
    # Runs automatically every day at midnight (UTC)
    - cron: '0 0 * * *'
  # manual trigger
  workflow_dispatch: 

jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: "true" # show total coding time
          TIME_RANGE: "all_time"
